version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8000:8000"
    environment:
      PAMPS_DB__uri: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-pamps}"
      PAMPS_DB__connect_args: "{}"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pamps-network
    command: >
      sh -c "alembic upgrade head &&
             uvicorn pamps.app:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/home/app/api
    stdin_open: true
    tty: true

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-pamps}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    env_file:
      - .env
    networks:
      - pamps-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local

networks:
  pamps-network:
    driver: bridge
